services:
  redis:
    image: redis:7.0.4
    ports:
      - "6379:6379"

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"

  celery:
    build: .
    working_dir: /code/habrclone
    command: celery -A habrclone worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
      - rabbitmq

  web:
    build: .
    working_dir: /code/habrclone
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    restart: "always"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - rabbitmq