# Generated by Django 5.0.6 on 2024-08-11 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('publications', '0002_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='publication_content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('post', 'article', 'news')}, on_delete=django.db.models.deletion.CASCADE, related_name='publication_content_types', to='contenttypes.contenttype'),
        ),
    ]
