# Generated by Django 5.0.6 on 2024-07-31 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_remove_post_content_type_remove_post_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
