# Generated by Django 5.0.6 on 2024-08-12 06:55

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='news',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
