# Generated by Django 5.0.6 on 2024-08-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
