# Generated by Django 5.0.6 on 2024-08-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='intro_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
